services:
  hawser:
    image: ghcr.io/finsys/hawser:latest
    pull_policy: always
    container_name: hawser
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKHAND_SERVER_URL=${DOCKHAND_SERVER_URL}
      - TOKEN=${TOKEN}
      - TZ=Australia/Melbourne
    healthcheck:
      test: ["CMD-SHELL", "echo ok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s