services:
  file-browser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    hostname:  filebrowser
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - TZ=Australia/Melbourne
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt:/srv # This is the location which Filebrowser would see when it starts up
      - /opt/production/filebrowser:/database.db
    security_opt:
      - no-new-privileges:true