services:
  file-browser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    hostname:  filebrowser
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - 8081:80
    environment:
      - TZ=Australia/Melbourne
      # - PUID=1000
      # - PGID=1000
    volumes:
      - /opt:/srv # This is the location which Filebrowser would see when it starts up
      - /opt/production/filebrowser.db:/database/filebrowser.db
      - /opt/production/settings.json:/.filebrowser.json
    # security_opt:
    #   - no-new-privileges:true