services:
  glance-docker-container-ext:
    image: dvdandroid/glance-docker-container-ext:latest
    container_name: glance-docker-container-ext
    pid: host
    uts: host
    restart: always
    labels:
      glance.enable: true
      glance.name: Glance Agent
      glance.description: "Glance Agent"
      glance.url: "http://192.168.147.219"
      glance.icon: "./assets/imgs/docker.svg"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT=8081  # Optional, default is 8081
    ports:
      - "6666:8081"  # Host:6666 -> Container:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "echo ok"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
