services:
  postgres:
    image: postgres:16-alpine
    pull_policy: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: dockhand
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dockhand
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - /var/lib/docker/volumes/dockhand_postgres_data/_data:/var/lib/postgresql/data # ← Bind mount to existing volume data
    healthcheck:
      test: ["CMD-SHELL", "echo ok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s


  dockhand:
    image: fnsys/dockhand:latest
    pull_policy: always
    ports:
      - 4000:3000
    environment:
      DATABASE_URL: postgres://dockhand:${POSTGRES_PASSWORD}@postgres:5432/dockhand
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - dockhand_data:/app/data
      - /var/lib/docker/volumes/dockhand_dockhand_data/_data:/app/data # ← Bind mount to existing volume data
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "echo ok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s


# volumes:
#   postgres_data:
#   dockhand_data: